[project]
name = "lmsociety"
version = "0.1.0"
description = "A multi-agent LLM debate simulation platform"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arize-phoenix>=13.15.0",
    "chromadb>=1.5.4",
    "click>=8.3.1",
    "click-shell>=2.1",
    "dspy>=3.0.4",
    "fastapi[all]>=0.128.0",
    "langchain-google-genai>=4.1.2",
    "langchain-huggingface>=1.2.0",
    "langchain-openai>=1.1.6",
    "numpy>=2.4.3",
    "opentelemetry-exporter-otlp>=1.40.0",
    "opentelemetry-sdk>=1.40.0",
    "openinference-instrumentation-dspy>=0.1.0",
    "openinference-instrumentation-langchain>=0.1.0",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.22",
    "rich>=14.2.0",
    "ruff>=0.14.10",
    "setuptools>=80.9.0",
    "streamlit>=1.55.0",
    "textual>=6.11.0",
    "textual-dev>=1.8.0",
    "typer>=0.21.0",
    "uvicorn>=0.40.0",
    "opentelemetry-instrumentation-fastapi>=0.61b0",
    "arize-otel>=0.11.0",
    "sqlalchemy>=2.0.45",
]

[tool.ruff.lint]
ignore = ["E402"]

#[project.scripts]
#lmsociety = "cli_app.cli_shell:lmsociety"

#[build-system]
#requires = ["setuptools", "wheel"]
#build-backend = "setuptools.build_meta"
